"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { Spinner } from "./Spinner";
import Image from "next/image";

type Step="enter-phone"|"enter-code";
const SG_PREFIX="+65";
export function LoginForm(){
 const [welcome,setWelcome]=useState(true); const [step,setStep]=useState<Step>("enter-phone"); const [phone,setPhone]=useState(""); const [code,setCode]=useState(""); const [loading,startTransition]=useTransition(); const [error,setError]=useState<string|null>(null); const [googleLoading,setGoogleLoading]=useState(false); const supabase=createClient(); const router=useRouter(); const fullPhone=`${SG_PREFIX}${phone.replace(/\D/g,"")}`;
 async function handleGoogleSignIn(){if(googleLoading)return;setGoogleLoading(true);setError(null);const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error){setError(error.message);setGoogleLoading(false)}}
 function handleSendCode(e:React.FormEvent){e.preventDefault();if(loading)return;setError(null);startTransition(async()=>{const {error}=await supabase.auth.signInWithOtp({phone:fullPhone});if(error){setError(error.message);return}setStep("enter-code")})}
 function handleVerifyCode(e:React.FormEvent){e.preventDefault();if(loading)return;setError(null);startTransition(async()=>{const {error}=await supabase.auth.verifyOtp({phone:fullPhone,token:code,type:"sms"});if(error){setError(error.message);return}router.push("/");router.refresh()})}
 if (welcome) return <div className="kb-welcome-screen"><div className="kb-welcome-photo"><Image src="/categories/home-cooks.jpg" alt="Local food" fill sizes="100vw" className="object-cover" priority/><div className="kb-welcome-shade"/><div className="relative z-10 flex min-h-screen flex-col justify-between p-7 text-white"><div className="pt-7"><Image src="/brand/logo-full.png" alt="Kopi Boy" width={190} height={70} className="h-16 w-auto object-contain brightness-0 invert" priority/><h1 className="mt-8 text-4xl font-black leading-[1.03] tracking-tight">Local Food<br/>Local People<br/>Delivered to You</h1><p className="mt-4 max-w-[18rem] text-sm leading-6 text-white/80">Discover home cooks, hawkers and neighbourhood favourites.</p></div><div className="pb-4"><button onClick={()=>setWelcome(false)} className="kb-primary-button w-full">Get Started</button><button onClick={()=>setWelcome(false)} className="mt-3 w-full rounded-2xl border border-white/60 bg-black/35 py-4 text-sm font-black text-white backdrop-blur">Sign In</button></div></div></div></div>;
 return <div className="kb-login-shell"><div className="kb-login-card"><div className="text-center"><Image src="/brand/logo-full.png" alt="Kopi Boy" width={150} height={56} className="mx-auto h-14 w-auto object-contain" priority/><p className="kb-eyebrow mt-5">WELCOME TO KOPI BOY</p><h1 className="mt-2 text-3xl font-black tracking-tight">Local food.<br/>Local people.</h1><p className="mt-3 text-sm leading-6 text-slate-500">Sign in to order from home cooks, hawkers and neighbourhood food businesses.</p></div>
 <button onClick={handleGoogleSignIn} disabled={googleLoading||loading} className="kb-google-button mt-7">{googleLoading?<Spinner size={18}/>:<GoogleIcon/>}{googleLoading?"Redirecting…":"Continue with Google"}</button>
 <div className="my-5 flex items-center gap-3"><span className="h-px flex-1 bg-slate-200"/><span className="text-xs font-bold text-slate-400">OR</span><span className="h-px flex-1 bg-slate-200"/></div>
 {step==="enter-phone"?<form onSubmit={handleSendCode} className="space-y-3"><div className="kb-phone-input"><span>{SG_PREFIX}</span><input type="tel" inputMode="numeric" required value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,"").slice(0,8))} placeholder="9123 4567"/></div><button type="submit" disabled={loading||googleLoading||phone.length<8} className="kb-primary-button w-full">{loading&&<Spinner/>}{loading?"Sending code…":"Continue with phone"}</button></form>:<form onSubmit={handleVerifyCode} className="space-y-3"><p className="text-sm text-slate-500">Enter the 6-digit code sent to <b className="text-slate-800">{fullPhone}</b>.</p><input type="text" inputMode="numeric" required value={code} onChange={e=>setCode(e.target.value)} placeholder="123456" className="kb-code-input"/><button type="submit" disabled={loading||googleLoading} className="kb-primary-button w-full">{loading&&<Spinner/>}{loading?"Verifying…":"Verify & continue"}</button><button type="button" onClick={()=>setStep("enter-phone")} className="w-full text-sm font-semibold text-slate-500">Use a different number</button></form>}
 {error&&<p className="mt-4 rounded-2xl bg-red-50 p-3 text-sm font-semibold text-red-600">{error}</p>}
 <p className="mt-6 text-center text-[11px] leading-5 text-slate-400">By continuing, you agree to use Kopi Boy for local food ordering and delivery.</p>
 </div></div>;
}
function GoogleIcon(){return <svg width="18" height="18" viewBox="0 0 24 24"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>}
